language: java
install: true

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      branch: master
      condition: $IS_RELEASE = true
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - ./manychat-java-api/manychat-api-example/build/libs/manychat-api-example-*
    skip_cleanup: true
    on:
      branch: master
      draft: true