language: java
install: true

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build

deploy:
  skip_cleanup: true
  on:
    branch: master
    condition: $IS_RELEASE = true
  - provider: script
    script: ./gradlew bintrayUpload