language: java
install: true

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  on:
    branch: master
    condition: $IS_RELEASE = true