language: java
install: true

jdk:
  - openjdk8

script:
  - ./gradlew clean build

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: script
    script: ./gradlew githubRelease
    skip_cleanup: true
    on:
      branch: master
      tags: true
